theme: minima
title: Centro Juvenil Salesianos Deusto
list_title: Evangelio Actualizado
author: Centro Juvenil Salesianos Deusto
description: Bienvenid@ al evangelio actualizado creado por el Centro Juvenil Salesiano de Deusto (Bilbao). En este lugar, podrás encontrar qué dice la Palabra para las situaciones cotidianas en la vida del siglo XXI.
plugins:
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true