theme: minima
title: Centro Juvenil Salesianos Deusto
list_title: Evangelio Actualizado
author: Centro Juvenil Salesianos Deusto
description: La Palabra en el siglo XXI.
plugins:
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true